### ISSUE TITLE
incorrect use of RcppArmadillo / Armadillo within R environment

### ISSUE THREAD

**Issue by conradsnicta** [HPDell/hgwrr#10]
@HPDell The hgwrr package for R incorrectly uses the armadillo header within R environment.

The hgwrr package erroneously includes the `<armadillo>` header instead of `<RcppArmadillo.h>` in several places:
* https://github.com/cran/hgwrr/blob/9bd6adfe297134fa32b05306f6eed7d150a6da7c/src/hlmgwr.h#L5
* https://github.com/cran/hgwrr/blob/9bd6adfe297134fa32b05306f6eed7d150a6da7c/src/hlmgwr.cpp#L10

`<RcppArmadillo.h>` is a wrapper around `<armadillo>`, and configures armadillo internals for compatibility with the R environment.

By *not* including `<RcppArmadillo.h>`, the hgwrr package ends up using an "unconfigured" instance of armadillo.  This leads to problems like the use of `std::cerr`.

Additionally, the hgwrr package defines `ARMA_NO_DEBUG`, which was always risky and ill-advised.  Newer versions of Armadillo ignore the old `ARMA_NO_DEBUG` macro.
* https://github.com/cran/hgwrr/blob/9bd6adfe297134fa32b05306f6eed7d150a6da7c/src/Makevars.in#L17

Related issue: https://github.com/RcppCore/RcppArmadillo/issues/446

**Comment by HPDell** [comment]
Hi @conradsnicta , thanks for pointing this out. This package is firstly developed as a cpp library and then a R wrapper is added. However, the cpp lib, which is not developed in a R environment, use armadillo to do matrix operations. In this case, if I use RcppArmadillo header in the R package, symbols of same names would have different memory sizes and could cause errors. 

I have found two ways to fix this issue. 

- Replace all the armadillo header with RcppArmadillo header by injecting codes in the cpp library. 
- Reconfigure armadillo with compile flags to make sure symbols in Rcpp sources and cpp lib sources are the same. 

The former one is how I fix the cerr issues in previous versions. It works for this instance but once a cpp library contains too many `#include <armadillo>` lines it would be annoying to fix each of them.
